apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
  namespace: devops
spec:
  type: LoadBalancer
  selector:
    app: sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

