name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Build and push Docker image
      run: |
        gcloud auth configure-docker
        docker build -t gcr.io/focused-clock-449509-e9/sample-app:latest .
        docker push gcr.io/focused-clock-449509-e9/sample-app:latest

    - name: Deploy to GKE
      run: |
        kubectl apply -f manifests/deployment.yaml
        kubectl apply -f manifests/service.yaml
    - name: Set GCP Project
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

